//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingRepository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsingRepository.Resources.ProductResource", typeof(ProductResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string DisplayCategory {
            get {
                return ResourceManager.GetString("DisplayCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DisplayDescription {
            get {
                return ResourceManager.GetString("DisplayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string DisplayPrice {
            get {
                return ResourceManager.GetString("DisplayPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string DisplayStock {
            get {
                return ResourceManager.GetString("DisplayStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Field must be less than 500 character.
        /// </summary>
        public static string MaxDescription {
            get {
                return ResourceManager.GetString("MaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name must be greater than 3 characters and less than 50 characters.
        /// </summary>
        public static string MinMaxName {
            get {
                return ResourceManager.GetString("MinMaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Date.
        /// </summary>
        public static string ProductDate {
            get {
                return ResourceManager.GetString("ProductDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Image.
        /// </summary>
        public static string ProductImage {
            get {
                return ResourceManager.GetString("ProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Field must be selected.
        /// </summary>
        public static string RequiredCategory {
            get {
                return ResourceManager.GetString("RequiredCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description field is Required.
        /// </summary>
        public static string RequiredDescription {
            get {
                return ResourceManager.GetString("RequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name Field is Required.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product Price is Required.
        /// </summary>
        public static string RequiredPrice {
            get {
                return ResourceManager.GetString("RequiredPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Field is Required.
        /// </summary>
        public static string RequiredStock {
            get {
                return ResourceManager.GetString("RequiredStock", resourceCulture);
            }
        }
    }
}
